language: python
os: linux

arch:
       - "amd64"
       - "arm64-graviton2"
       - "ppc64le"
python:
       - "3.7"

install:
       - python -m pip install pip==20.2
       - python -m pip install --upgrade setuptools
       - python -m pip install --progress-bar=off -e ./ml-agents-envs
       - python -m pip install --progress-bar=off -e ./ml-agents
       - python -m pip install --progress-bar=off -r test_requirements.txt
       - python -m pip install --progress-bar=off -e ./gym-unity
       - pip freeze

branches:
    only:
        - master        

script: 
        - pytest -vs --durations 20        
       
